/*
* generated by Xtext
*/
package org.hibnet.jst.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JstProposalProvider extends AbstractJstProposalProvider {

}
